baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Roberto Corti Web Page"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

params:
  title: "Roberto Corti"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo_white.png"

  # Whether the fade animations on the home page will be enabled
  animate: true

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left


  # Hero
  hero:
    enable: true
    intro: ""
    title: "Roberto Corti."
    subtitle: "Personal Blog"
    content: "Data scientist, math and programming enthusiast."
    image: /images/hero.svg
    button:
      enable: false
      name: "Hello"
      url: "#experience"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/RobertoCorti
        - icon: fab fa-twitter
          url: https://twitter.com/RobertoCorti29
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/roberto-corti-723346181


  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/foto.png"
    content: |-
      I am a data scientist with a passion for math, statistics and software development. I have a background in physics, and I have a strong interest in the intersection of technology and math. I am currently working as a data scientist at [Fastweb](https://fastweb.it) in Milan, Italy. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "C++"
        - "R"
        - "Docker"
        - "AWS Sagemaker"

 # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Data Scientist"
        company: "Fastweb"
        companyUrl: "https://www.fastweb.it/"
        date: "Jan 2022 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a data scientist at [Fastweb](https://fastweb.it) in Milan, Italy. I have developed and deployed machine learning models used to drive and leverage some business processes such as upselling activity and customer experience monitoring."

      - job: "Junior Data Scientist"
        company: "Orobix"
        companyUrl: "https://orobix.com"
        date: "Nov 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://orobix.com/en/anomaly-detection-for-predictive-maintenance/"
        content: |
          I worked as a data scientist and software developer at [Orobix](https://orobix.com) in Bergamo, Italy for more than one year. I was mainly involved in the development of [Detectiv.ai](https://orobix.com/detectiv-ai/). I started as an intern working on R&D activities related on anomaly detection in time series. After that, my job was to develop several features of this product and deploy to production. 

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master in Data Science and Scientific Computing"
        school:
          name: "University of Trieste and Scuola Internazionale Superiore di Studi Avanzati, Trieste (Italy)"
          url: "https://dssc.units.it/"
        date: "2019 - 2021"
        GPA: "110 / 110 cum Laude"
        content: |-
          Extracurricular Activities
            - Internship @ [Orobix](https://orobix.com/) where I had the chance to study machine learning solutions for [Detectiv.ai](https://orobix.com/en/anomaly-detection-for-predictive-maintenance/), a software that artificial intelligence for real-time detection of anomalies (outliers) in time series from sensors placed in the field.
      - title: "Bachelor of Science in Physics"
        school:
          name: "Università degli Studi di Milano, Milan (Italy)"
          url: "https://www.unimi.it/it/corsi/corsi-di-laurea/fisica"
        date: "2015 - 2018"
        GPA: "104 out of 110"
        content: |-

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: roberto.corti@fastweb.it
    btnName: Mail me

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/RobertoCorti
      linkedin: https://www.linkedin.com/in/roberto-corti-723346181/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false